### ISSUE TITLE
you need to provide the full path to the executable in the LSP-julia package settings.

### ISSUE THREAD

**Issue by StefanPofahl** [sublimelsp/LSP-julia#22]
In the isntallation / configuration instructions it is mentioned, that the full-path of the julia executable needs to be specified,
if it is not in the %PATH%.
What is the correct way to specify the full-path of the julia executable?

**Comment by jwortmann** [comment]
I can only show an example for Windows, because personally I only use Windows.

For example I currently have Julia 1.8.3 in my *Path* environment variable, and it is used for the language server and "Open Julia REPL" command. But I have also still a previous version 1.8.0 installed, and if I specify
```json
{
    "julia_executable_path": "C:\\Users\\jwortmann\\AppData\\Local\\Programs\\Julia-1.8.0\\bin\\julia.exe",
}
```
in the LSP-julia settings, then this one will be used instead. Note that the backslashes in Windows paths need to be escaped in JSON.

**Comment by jwortmann** [comment]
Okay it seems you are relatively new to Sublime Text in general. Regarding settings files, keybindings etc., the file on the righthand side is always the user file and the file on the left is the readonly built-in file with the default values. Settings in the user file override the default settings.

If you want to use the Julia REPL within Sublime Text, make sure you have the Terminus package installed. Then there should be an entry in the command palette "LSP-julia: Open Julia REPL in Panel" (or "... in Tab") to start the Julia REPL. If you have a Julia file open, you can use <kbd>Alt</kbd>+<kbd>Enter</kbd> to run a selection or the current code block in the REPL. To change the key binding, select *Preferences > Key Bindings* from the main menu and copy the code from https://github.com/sublimelsp/LSP-julia/blob/7ffaecf040a3d7c0123c47e3bb093d5b7316e9bf/Default.sublime-keymap#L2-L17 to the righthand side into your user file.
It is set to <kbd>Alt</kbd>+<kbd>Enter</kbd> by default because e.g. <kbd>Ctrl</kbd>+<kbd>Enter</kbd> already has a built-in keybinding in Sublime Text, and this is what VS Code used to use.

For the other key binding to run a code *cell*, you need to put special comments into your source code to signalize the code cells, see the readme file in this repository.

Btw, all this is built-in in LSP-julia, so the only other package you need for this is the Terminus package.

One other important thing is that the language server heavily relies on environments, i.e. you usually should open a folder in Sublime Text via *File > Open Folder...* or by dragging it into the sidebar (or use Sublime's project files). Ideally this folder should have a *Project.toml* file in it, because the language server uses the packages specified therein to provide auto-complete suggestions for example. So if you only open a single Julia file instead, many things won't work as if you had opened a folder/project. If you have opened a folder, the language server should find the correct environment when it initializes. But you can also change it manually via "LSP-julia: Change Current Environment" from the command palette.

**Comment by jwortmann** [comment]
By the way, the "Run code block/cell" functionality is just a simple copy and paste to the Julia REPL. So if you run for example `include("some/file.jl")`, it will only work if the path is relative to the current working directory (the Julia REPL is started in the folder of the active file by default).

And there is no built-in way to run an entire Julia file as if you would call `julia somefile.jl` from a shell. This usually done via [Build Systems](https://www.sublimetext.com/docs/build_systems.html) in Sublime Text, and there is an open pull request in the Julia package at https://github.com/JuliaEditorSupport/Julia-sublime/pull/80 to add such a build system file. But it has already been open for years and I doubt that it will ever be merged, so if you want to use a build system, you will need to create your own and put it into your User folder.

**Comment by StefanPofahl** [comment]
Thank you so much! Especially for the hint, that "Open folder" should open a folder where the `Project.toml` of the environment is hosted.
